### PR TITLE
Alex Glasses

### PR DESCRIPTION
**Pull request by ajholland**
Alex Glasses

### CODE REVIEW

**Comment by ajholland** [comment]
@BGR360 please review!

**Comment by ajholland** [comment]
@BGR360 CI has passed! Please review!

**Comment by BGR360** [comment]
New page exists but new emote not visible in directory page. Need to add to `alexes` in `config.json`.

**Comment by ajholland** [comment]
@BGR360 Appreciations for the quick and thorough review of the changes proposed, I have adjusted them, hopefully to your satisfaction. On my side, I see the application working as intended. Best Regards, JustNoAlex

**Comment by BGR360** [comment]
Thanks, LGTM. I'll put this in myself tonight.

**Pull request closed without merging**
